[package]
name = "ekubo_rb"
version = "0.1.0"
description = "Owner for the Ekubo core contract that allows anyone to trigger buybacks via TWAMM"
homepage = "https://ekubo.org"
cairo-version = "2.7.1"
edition = '2024_07'

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry" }
starknet = "=2.7.1"

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
casm = true

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/fHMTeGf5b1PIw83HVoo7JUCpSr0THrxw"
block_id.tag = "Latest"
